# Generated by Django 5.2.4 on 2025-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_code', models.CharField(help_text="Unique identifier for the setting (e.g., 'theme_config', 'api_limits')", max_length=100, unique=True)),
                ('setting_value', models.JSONField(help_text='JSON value for the setting configuration')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this setting controls')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'utils_settings',
                'ordering': ['setting_code'],
            },
        ),
    ]
