# Generated by Django 5.2.4 on 2025-08-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDB movie ID')),
                ('title', models.CharField(help_text='Movie title', max_length=255)),
                ('poster_path', models.CharField(blank=True, help_text='Movie poster path', max_length=255, null=True)),
                ('overview', models.TextField(blank=True, help_text='Movie overview/description')),
                ('release_date', models.DateField(blank=True, help_text='Movie release date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the movie was added to favorites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_movies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_favori_user_id_b31f18_idx'), models.Index(fields=['tmdb_id'], name='user_favori_tmdb_id_0ab7f9_idx')],
                'unique_together': {('user', 'tmdb_id')},
            },
        ),
    ]
